kws={
  'back flip': keys('alt+tab'),
  'be quiet,be silent,silence': say('going silent') & mute(),
  'beginning of file': keys('ctrl+home'),
  'check email': 'thunderbird &',
  'clear': 'clear',
  'close assistant': play('beep_close.wav') and mind('boot'),
  'close': keys('Alt+F4'),
  'close *': close('*'),
  'close other tabs': keys('Control+Shift+F4'),
  'close project m': close('projectM-pulseaudio'),
  'close status': close('htop'),
  'close tab': keys('ctrl+w'),
  'close terminal': close('terminal'),
  'close window': keys('ctrl+w'),
  'copy': keys('ctrl+c'),
  'cut': keys('ctrl+x'),
  'down': keys('page_down'),
  'username': say(_sys('user')),
  'hostname': say(_sys('host')),
  'address': say(_sys('ip')),
  'system info':say('User name %s\nHost name %s\nIP address %s\nOperating System %s'%(_sys('user'),_sys('host'),_sys('ip'),_sys('os'))),
  'enter': keys('return'),
  'escape': keys('esc'),
  'end': keys('end'),
  'end of file': keys('ctrl+end'),
  'find': keys('ctrl+F'),
  'fullscreen': keys('F11'),
  'go to *': activate('*'),
  'hello root': say('greetings sir'),
  'home': keys('Home'),
  'invite everyone': 'while true; do xdotool click 1; sleep .1; xdotool key Down; xdotool click 1; xdotool mousemove_relative --sync 0 -22; xdotool click 1; sleep .1; xdotool mousemove_relative --sync 0 22; done',
  'list': keys('ls+return'),
  'list access points': 'sudo iwlist wlp4s0 scan , less',
  'list block devices': 'lsblk -fp',
  'list modules': 'lsmod',
  'list network devices': 'ip link',
  'list processes': 'ps aux , less &',
  'matrix': sys_exec('cmatrix') and say('there is no spoon...'),
  'maximize window': 'xdotool key alt+space && sleep .1 && xdotool key x',
  'minimize window': 'xdotool key alt+space && sleep .1 && xdotool key n',
  'new file': 'xdotool key Control+n &',
  'next tab': 'xdotool key Control+Page_Down &',
  'new tab': 'xdotool key Control+t &',
  'ok computer': say('fitter, happier, more productive, comfortable, not drinking too much, regular exercise at the gym, three days a week'),
  'open arch wiki': '$BROWSER https://wiki.archlinux.org &',
  'open assistant forum': '$BROWSER http://openassistant.org/community/ &',
  'open commands': 'pycharm &',
  'open commands file': 'pycharm &',
  'open editor': 'subl &',
  'open project em': 'projectM-pulseaudio &',
  'open facebook': '$BROWSER https://www.facebook.com &',
  'open firefox': '$BROWSER &',
  'open web': '$BROWSER &',
  'open the web': '$BROWSER &',
  'open status': '$TERMINAL htop && xdotool key alt+space && sleep .1 && xdotool key x &',
  'open stella': './mind/stella/words/hello.py , $VOICE & ./run.sh -c -H20 -m0 -M mind/stella',
  'open tab': 'xdotool key Control+t &',
  'open terminal': '$TERMINAL && wmctrl -a terminal &',
  'open the pod bay doors': 'feh -F ./mind/root_arch/images/hal.jpg & aplay ./mind/root_arch/sounds/sorry_dave.wav && sleep .5 && pkill -f feh &',
  'open youtube': '$BROWSER https://www.youtube.com &',
  'page up': 'xdotool key Page_Up',
  'page down': 'xdotool key Page_Down',
  'paste': 'xdotool key Control+v &',
  'play': 'xdotool key Shift+A &',
  'previous tab': 'xdotool key Control+Page_Up &',
  'print mind directory': 'echo $MINDDIR',
  'print working directory': 'pwd -P',
  'quit program': 'xdotool key Control+q',
  'quit web': 'wmctrl -c $BROWSER',
  'quit the web': 'wmctrl -c $BROWSER',
  'quit status': 'pkill -f htop &',
  'quit thunderbird': 'wmctrl -c thunderbird',
  'reboot assistant': 'espeak  -s 133 rebooting &> /dev/null & ./run.sh -c -H20 -m1 -M mind/root_arch && pkill -of root_arch',
  'record': 'xdotool key R &',
  'red pill': say('all delusion is forever temporary...') & close('cmatrix'),
  'rewind': 'xdotool key Home &',
  'root': say('yes sir'),
  'root mind': say('yes sir'),
  'run diagnostics': './mind/root_arch/words/diagnostics.sh',
  'save document': 'xdotool key Control+s && espeak -s 133 saved',
  'save file': 'xdotool key Control+s && espeak -s 133 saved',
  'select all': 'xdotool key Control+a',
  'scroll down': 'xdotool key Page_Down',
  'scroll up': 'xdotool key Page_Up',
  'search web': '$BROWSER https://duckduckgo.com && sleep 1 && xdotool key Tab Return &',
  'show status': '$TERMINAL htop && xdotool key alt+space && sleep .1 && xdotool key x &',
  'show useful commands': 'cat ~/useful_commands.txt',
  'sing a song': 'aplay ./mind/root_arch/sounds/daisy.wav',
  'sing me a song': 'aplay ./mind/root_arch/sounds/daisy.wav',
  'sing for me': 'aplay ./mind/root_arch/sounds/daisy.wav',
  'suspend machine': 'echo suspending machine , $VOICE && systemctl suspend',
  'switch to firefox': 'wmctrl -a firefox &',
  'switch to terminal': 'wmctrl -a terminal &',
  'system status': '$TERMINAL htop &',
  'talk to me': mute(0) & say('i am back...'),
  'tell me about you': "espeak -s 133 'i am the open assistant root mind... my job is to manage operating system control functions... open assistant is composed of three layers of minds... including boot... root... and user minds... the boot mind launches a root mind such as me... i am able to launch user minds such as stella...' &> /dev/null",
  'terminal': 'wmctrl -a terminal &',
  'time is it?': "espeak -s 133 'the time is' &> /dev/null && date +%l:%M | tee /dev/tty | espeak -s 133 &> /dev/null",
  'thanks root': play('play_a_game.wav'),
  'turn on wireless': 'sudo ip link set wlp4s0 up',
  'undo': 'xdotool key Control+z',
  'voice note': 'audacity &',
  'volume down': volume(-10),
  'volume mute': say('going silent') & mute(),
  'volume up': volume(10),
  'what day?': "espeak -s 133 'today is' &> /dev/null && date +%A | tee /dev/tty | espeak -s 133 &> /dev/null",
  'what day is?': "espeak -s 133 'today is' &> /dev/null && date +%A | tee /dev/tty | espeak -s 133 &> /dev/null",
  'what day is it?': 'date +%A | tee /dev/tty | espeak -s 133 &> /dev/null',
  'what day is it today?': "espeak -s 133 'today is' &> /dev/null && date +%A | tee /dev/tty | espeak -s 133 &> /dev/null",
  'what is the time?': 'saytime | espeak -s 133',
  'what is the weather today?': './mind/stella/words/weather.py | tee /dev/tty |  espeak -s 133 &> /dev/null',
  'what is the weather?': './mind/stella/words/weather.py | tee /dev/tty |  espeak -s 133 &> /dev/null',
  'what time?': "espeak -s 133 'the time is' &> /dev/null && date +%l:%M | tee /dev/tty | espeak -s 133 &> /dev/null",
  'what time is?': "espeak -s 133 'the time is' &> /dev/null && date +%l:%M | tee /dev/tty | espeak -s 133 &> /dev/null",
  'what time is it?': "espeak -s 133 'the time is' &> /dev/null && date +%l:%M | tee /dev/tty | espeak -s 133 &> /dev/null"
}
